### ISSUE TITLE
update variable names in documentation.ipynb to follow PEP 8 Guidelines

### ISSUE THREAD

**Issue by jennmcguire** [phys201/FluorescenceSpectroscopy#3]
https://peps.python.org/pep-0008/#package-and-module-names

"Function names should be lowercase, with words separated by underscores as necessary to improve readability.
Variable names follow the same convention as function names.
mixedCase is allowed only in contexts where that’s already the prevailing style (e.g. threading.py), to retain backwards compatibility."

**Comment by bdelwood** [comment]
I think I fixed them in 6e901a07598dde86604e34ee935b8d77593937bd
