### ISSUE TITLE
consider different priors

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/FluorescenceSpectroscopy#4]
Uniform priors aren't usually the best choice for NUTS sampling, because the gradients aren't defined at the boundary.  So unless you really have hard bounds on the parameters, it's better to use either a Normal prior or a Gamma prior (for parameters that are positive).  Also you'll want to explain your choice of priors in the documentation notebook.

**Comment by vnmanoharan** [comment]
Reopening.  For parameters that are always positive, use a Gamma prior instead of a Normal.  With a gamma distribution, you can specify the mean and sigma, just like with a normal distribution, but the parameter will never go below zero.  With a normal distribution, there's always a chance that the sampler will choose a negative value, in which case you might get divergences or NaNs if the model predictions are nonphysical.

**Comment by bdelwood** [comment]
Fixed #20
