### ISSUE TITLE
sampler tweaks

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/FluorescenceSpectroscopy#5]
For NUTS sampling, you don't want to start at the MAP because the gradients are zero there.  So I'd recommend removing the `start=pm.find_MAP()` argument in your `pm.sample()` statement.  Also it would be good to see some comparison between the inferred and true values for your simulated data.

**Comment by bdelwood** [comment]
#8 was only a partial fix, still have 
> it would be good to see some comparison between the inferred and true values for your simulated data.

to do

**Comment by bdelwood** [comment]
Fixed in b62f86f00a85700bcdc590e4896779961dcad3f3 by final plot comparing inferred from real parameter values.
